trigger:
- メイン
pool:
  vmImage: ubuntu-latest

variables:
  build Configuration: ' Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName:  'dotnet build $(buildConfiguration)'