trigger:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '6.x'
  NODE_OPTIONS: --max_old_space_size=8192

steps:
- task: PowerShell@2
  displayName: 'Build(UAT)'
  inputs:
    targetType:'inline'
    script: |
      .\devenv /?
