trigger:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

steps:
- task: PowerShell@2
  displayName: 'Build(UAT)'
  inputs:
    targetType: 'inline'
    script: |
      cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE"
      ./devenv /?
