trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '6.x'
  NODE_OPTIONS: --max_old_space_size=8192

steps:
- task: UseNode@1
  inputs:
    version: '22.7.0'
  displayName: 'Install Node.js'

- script: |
    node -e 'console.log(Math.floor(v8.getHeapStatistics().heap_size_limit/1024/1024))'
  displayName: 'Run Node.js Command'
